language: node_js
node_js:
 - "lts/*"
before_install:
 - curl -o- -L https://yarnpkg.com/install.sh | bash
 - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
script:
  - yarn test
  - yarn coverage