language: node_js
node_js:
 - "lts/*"
before_install:
 - curl -o- -L https://yarnpkg.com/install.sh | bash
 - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add -g codecov
  - yarn install
cache:
  yarn: true
  directories:
      - node_modules
script:
  - yarn lint
  - yarn build
  - yarn test -- --coverage
  - codecov